<?php

namespace Elt\LanguageCodes;

class LanguageCodeLookup
{
    private static $language_codes = [
        'afrikaans' => 'af',
        'akan' => 'ak',
        'albanian' => 'sq',
        'amharic' => 'am',
        'arabic' => 'ar',
        'armenian' => 'hy',
        'assamese' => 'as',
        'aymara' => 'ay',
        'azerbaijani' => 'az',
        'baluchi' => 'bal',
        'bambara' => 'bm',
        'bangla' => 'bn',
        'bengali' => 'bn',
        'belarusian' => 'be',
        'bhojpuri' => 'bho',
        'bosnian' => 'bs',
        'bulgarian' => 'bg',
        'burmese' => 'my',
        'catalan' => 'ca',
        'cebuano' => 'ceb',
        'chichewa' => 'ny',
        'chinese-simplified' => 'zh-cn',
        'chinese-traditional' => 'zh-tw',
        'corsican' => 'co',
        'croatian' => 'hr',
        'czech' => 'cs',
        'danish' => 'da',
        'dari' => 'fa-AF',
        'dhivehi' => 'dv',
        'dogri' => 'doi',
        'dutch' => 'nl',
        'dzongkha' => 'dz',
        'english' => 'en',
        'esperanto' => 'eo',
        'estonian' => 'et',
        'ewe' => 'ee',
        'filipino' => 'tl',
        'finnish' => 'fi',
        'french' => 'fr',
        'frisian' => 'fy',
        'galician' => 'gl',
        'georgian' => 'ka',
        'german' => 'de',
        'greek' => 'el',
        'guarani' => 'gn',
        'gujarati' => 'gu',
        'haitian creole' => 'ht',
        'hausa' => 'ha',
        'hawaiian' => 'haw',
        'hebrew' => 'he',
        'hiligaynon' => 'hil',
        'hindi' => 'hi',
        'hmong' => 'hmn',
        'hungarian' => 'hu',
        'icelandic' => 'is',
        'igbo' => 'ig',
        'ilocano' => 'ilo',
        'indonesian' => 'id',
        'irish' => 'ga',
        'italian' => 'it',
        'japanese' => 'ja',
        'javanese' => 'jv',
        'kannada' => 'kn',
        'kapampangan' => 'pam',
        'kazakh' => 'kk',
        'khasi' => 'kha',
        'khmer' => 'km',
        'kinyarwanda' => 'rw',
        'konkani' => 'gom',
        'korean' => 'ko',
        'krio' => 'kri',
        'kurdish' => 'ku',
        'kyrgyz' => 'ky',
        'lao' => 'lo',
        'latin' => 'la',
        'latvian' => 'lv',
        'lingala' => 'ln',
        'lithuanian' => 'lt',
        'luganda' => 'lg',
        'luxembourgish' => 'lb',
        'macedonian' => 'mk',
        'maithili' => 'mai',
        'malagasy' => 'mg',
        'malay' => 'ms',
        'malayalam' => 'ml',
        'maltese' => 'mt',
        'manipuri' => 'mni-mtei',
        'marathi' => 'mr',
        'marwadi' => 'mwr',
        'maori' => 'mi',
        'meiteilon' => 'mni-mtei',
        'mongolian' => 'mn',
        'mizo' => 'lus',
        'myanmar' => 'my',
        'nepali' => 'ne',
        'newari' => 'new',
        'norwegian' => 'no',
        'nyanja' => 'ny',
        'odia' => 'or',
        'oromo' => 'om',
        'pashto' => 'ps',
        'persian' => 'fa',
        'polish' => 'pl',
        'portuguese' => 'pt',
        'punjabi' => 'pa',
        'quechua' => 'qu',
        'romanian' => 'ro',
        'russian' => 'ru',
        'samoan' => 'sm',
        'sanskrit' => 'sa',
        'santali' => 'sat',
        'scots-gaelic' => 'gd',
        'sepedi' => 'nso',
        'serbian' => 'sr',
        'sesotho' => 'st',
        'shona' => 'sn',
        'simplified-chinese' => 'zh-cn',
        'sindhi' => 'sd',
        'sinhalese' => 'si',
        'sinhala' => 'si',
        'slovak' => 'sk',
        'slovenian' => 'sl',
        'somali' => 'so',
        'spanish' => 'es',
        'sundanese' => 'su',
        'swahili' => 'sw',
        'swedish' => 'sv',
        'tagalog' => 'tl',
        'tajik' => 'tg',
        'tamil' => 'ta',
        'tatar' => 'tt',
        'telugu' => 'te',
        'thai' => 'th',
        'tigrinya' => 'ti',
        'traditional-chinese' => 'zh-tw',
        'tsonga' => 'ts',
        'tulu' => 'tcy',
        'turkish' => 'tr',
        'turkmen' => 'tk',
        'twi' => 'ak',
        'ukrainian' => 'uk',
        'urdu' => 'ur',
        'uyghur' => 'ug',
        'uzbek' => 'uz',
        'vietnamese' => 'vi',
        'welsh' => 'cy',
        'xhosa' => 'xh',
        'yiddish' => 'yi',
        'yoruba' => 'yo',
        'zulu' => 'zu',
    ];

    /**
     * @throws LanguageLookupException
     */
    public static function getCode(string $language_name): string
    {
        $language_name = strtolower($language_name);
        if (array_key_exists($language_name, self::$language_codes)) {
            return self::$language_codes[$language_name];
        } else {
            throw new LanguageLookupException("Unknown language: $language_name");
        }
    }

    public static function getAllTwoDigitCodes(): array
    {
        return array_values(self::$language_codes);
    }
}
